# Summary - `numpy`

Summary of topics covered in Weeks 7-9

## Numpy module

In [1]:
# The numpy module must be imported to be used. The shorthand `np` is usually used for this.
import numpy as np

### Numpy arrays

[Week 7: Numpy Arrays](../Week7/Week7_VideoRecap1_NumpyArrays.ipynb); [Week 7: Questions](../Week7/Week7_10_Questions.ipynb); [Week 9: Multi-dimensional arrays and indexing](../Week9/Week9_VideoRecap2_MultiDimensionalArrays.ipynb)

**Array creation**

Documentation: [Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [2]:
# Numpy array objects can be created in lots of different ways to contain different values
# One way to create an array is directly from a list
arr1 = np.array([1, 2, 3])

In [3]:
# Another way is to create a range of numbers
lower = 1
upper = 10
step = 0.3
arr2 = np.arange(lower, upper, step)
print(arr2)
print(len(arr2))

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
30


In [4]:
# You can also create arrays of a given size (defined as an integer)
size = 30
arr3 = np.ones(size)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [5]:
# or shape (defined as a tuple of integers)
shape = (2, 3)
arr4 = np.zeros(shape)
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Arrays have properties of dtype (what type of values contained) and shape
print(arr2.dtype)
print(arr4.shape)

float64
(2, 3)


**Indexing**

Documentation: [indexing in numpy](https://numpy.org/doc/stable/reference/arrays.indexing.html)

In [7]:
# Arrays can be indexed in the same way as lists, using slicing
print(arr1[1:])

[2 3]


In [8]:
# Arrays can also be indexed based on their multi-dimensionality (using a comma)
print(arr4[1, 0])

0.0


In [9]:
# Arrays can be filtered (indexed) using a condition - Boolean array indexing
arr_gt_5 = arr2[arr2 > 5]
print(f"Length of original array: {len(arr2)}")
print(arr_gt_5)
print(f"Length of new, filtered array: {len(arr_gt_5)}")

Length of original array: 30
[5.2 5.5 5.8 6.1 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
Length of new, filtered array: 16


**Operators and combining arrays**

In [10]:
# Arrays can also be used directly with operators which will be applied for each element
arr1_multiply = arr1*2
print(arr1_multiply)

[2 4 6]


In [11]:
# Arrays can also be combined with each other if they have the right size / shape
print(len(arr2),len(arr3))
add = arr2 + arr3
print(add)

30 30
[ 2.   2.3  2.6  2.9  3.2  3.5  3.8  4.1  4.4  4.7  5.   5.3  5.6  5.9
  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9  9.2  9.5  9.8 10.1
 10.4 10.7]


### Numpy functions

[Week 7: Numpy functions](../Week7/Week7_VideoRecap2_NumpyFunctions.ipynb); [Week 7: Questions](../Week7/Week7_10_Questions.ipynb); [Week 7: Worked Example](../Week7/Week7_11_WorkedExample_BouncingBall.ipynb)

Documentation: [numpy statistical functions](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [12]:
## The numpy module contains lots of functions which can be used directly on an entire array
# Statistical functions
mean = np.mean(arr1)
print(mean)

2.0


Documentation: [numpy mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)

In [13]:
# Mathematical functions e.g. trigonometric
tan_x = np.tan(arr1)
print(tan_x)
print(len(tan_x))

[ 1.55740772 -2.18503986 -0.14254654]
3


In [14]:
# Mathematical functions e.g. exponents and logarithms
log_x = np.log10(arr1)
print(log_x)
print(len(log_x))

[0.         0.30103    0.47712125]
3


### Numpy random submodule

[Week 8: random submodule](../Week8/Week8_13_Numpy_Random.ipynb); [Week 8: worked example](../Week8/Week8_14_WorkedExample_RadioactiveDecay.ipynb); [Week 9: Random sampling](../Week9/Week9_VideoRecap1_RandomSampling.ipynb)

In [15]:
## The numpy function has a submodule called random which can be used
# to generate random numbers
# This needs to be imported
from numpy import random

**Random number generator**

Documentation: [numpy default random number generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng)

In [16]:
# First create the random number generator itself - initialisation value (seed) can be specified.
seed = 10    # This can be set to any number, is just to allow repeatable results.
rng = random.default_rng(seed)

**Generating random numbers**

Documentation: [using random() function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html)

In [17]:
# Random numbers can be created using the random number generator between 0.0 and 1.0
rng.random()

0.9560017096289753

In [18]:
# Multiple numbers can be created at once in whatever size (or shape) you want
size = 3
print(rng.random(size))

[0.20768181 0.82844489 0.14928212]


In [19]:
# These random numbers can be used to cover other ranges as well
start = 3
end = 10
numbers_0_1 = rng.random(size)
numbers_start_end = start + numbers_0_1 * (end-start)
print(numbers_0_1)
print(numbers_start_end)

[0.51280462 0.1359196  0.68903648]
[6.58963232 3.95143723 7.82325536]


Documentation: [using integers() function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers)

In [20]:
# Other functions can also be used to select random numbers such as integers
rng.integers(start,end,size=size)

array([5, 8, 3], dtype=int64)

Documentation: [using choice() function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html)

In [21]:
# Or by making a choice from a pre-existing list of options
rng.choice(arr1,size=size)

array([2, 2, 3])